version: "2"

# networks:
#   app-tier:
#     driver: bridge

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    image: python-sanic-mongodb-sample-app
    environment:
      - APP_HOST=127.0.0.1
      # - APP_CONFIG_PATH=./config.py
      # - MONGODB_USERNAME=user
      # - MONGODB_PASSWORD=password
      - MONGODB_HOST=mongodb
      - MONGODB_DATABASE=main
    volumes:
      - ./python-sanic-mongodb-sample-app:/app/
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    # networks:
    #   - app-tier
    tty: true

  mongodb:
    image: mongo:latest
    restart: always
    # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
      # - MONGODB_USERNAME=user
      # - MONGODB_PASSWORD=password
      # - MONGODB_DATABASE=app
      # - MONGODB_ROOT_PASSWORD=root
    # volumes:
    #   - main:/data/main
    #   - mongo-config:/data/configdb
    # networks:
    #   - app-tier

  # volumes:
  # main:
  # mongo-config: